/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "CyScBoostClk.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "pwm_pin_1_aliases.h"
#include "pwm_pin_1.h"
#include "PWM_1.h"
#include "adc_pin_3_aliases.h"
#include "adc_pin_3.h"
#include "adc_pin_2_aliases.h"
#include "adc_pin_2.h"
#include "isr_rx.h"
#include "PWM_0.h"
#include "Clock_1.h"
#include "pwm_pin_0_aliases.h"
#include "pwm_pin_0.h"
#include "ADC_0.h"
#include "adc_pin_0_aliases.h"
#include "adc_pin_0.h"
#include "adc_pin_1_aliases.h"
#include "adc_pin_1.h"
#include "AMux_0.h"
#include "Timer_1.h"
#include "median_timer.h"
#include "update_median_isr.h"
#include "PWM_2.h"
#include "pwm_pin_2_aliases.h"
#include "pwm_pin_2.h"
#include "PWM_3.h"
#include "pwm_pin_3_aliases.h"
#include "pwm_pin_3.h"
#include "EEPROM.h"
#include "UART_IntClock.h"
#include "ADC_0_IRQ.h"
#include "ADC_0_theACLK.h"
#include "ADC_0_Bypass_aliases.h"
#include "ADC_0_Bypass.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

